export { Scene } from './Scene';
export { BodyModel } from './BodyModel';
export { CameraRig } from './CameraRig';
export { LayerControls } from './LayerControls';
export { bodyParts, modeledSystems, getPartCenter } from './bodyParts';
export { useAnatomyModel, preloadAnatomyModel, type AnatomyModel } from './useAnatomyModel';
export { tagScene, type StructureIndex } from './tagStructures';
export { getStructureBounds, type StructureBounds } from './modelBounds';
export { MODEL_URLS, MODELED_SYSTEMS, MODELS_ENABLED, DRACO_DECODER_PATH } from './modelManifest';
export type { BodyPart, MeshDef, MeshKind, LoadedPart, MeshSource } from './viewer.types';
